[package]
name = "liblumen_beam"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
byteorder = "1.2"
libflate = "0.1"
num = "0.1"
glob = "0.2"
tempfile = "3.0.5"
failure = "0.1"
