[package]
name = "liblumen_beam"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>", "Luke Imhoff <Kronic.Deth@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
byteorder = "1.2"
libflate = "0.1"
num = "0.2"
failure = "0.1"
