[package]
name = "liblumen_codegen"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
edition = "2018"
publish = false

build = "build.rs"

[dependencies]
llvm-sys = "70"
libc = "0.2"
failure = "0.1"
tempfile = "3.0"
liblumen_diagnostics = { path = "../liblumen_diagnostics" }
liblumen_syntax = { path = "../liblumen_syntax" }

[build-dependencies]
cc = "1.0.25"
