[package]
name = "liblumen_codegen"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
edition = "2018"
publish = false

#build = "build.rs"

[dependencies]
libc = "0.2"
failure = "0.1"
tempfile = "3.0"
# eirproject/eir crates
libeir_diagnostics = { git = "https://github.com/eirproject/eir.git" }
libeir_intern = { git = "https://github.com/eirproject/eir.git" }
libeir_ir = { git = "https://github.com/eirproject/eir.git" }
libeir_passes = { git = "https://github.com/eirproject/eir.git" }
libeir_syntax_erl = { git = "https://github.com/eirproject/eir.git" }
# llvm crates
llvm-sys = { git = "https://github.com/lumen/llvm-sys.rs", branch = "llvm-9.0" }

[dependencies.inkwell]
git = "https://github.com/lumen/inkwell"
branch = "llvm-9.0"
features = ["llvm9-0"]

[build-dependencies]
cc = "1.0.32"
cmake = "0.1"
which = "2.0.1"
