[package]
name = "liblumen_rt_macros"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "^1.0"
proc-macro2 = "^1.0"

[dependencies.syn]
version = "^1.0"
features = ["full"]
