[package]
name = "liblumen_web"
version = "0.1.0"
authors = ["Luke Imhoff <Kronic.Deth@gmail.com>"]
edition = "2018"
publish = false
description = "Lumen bindings for Web APIs"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
anyhow = "1.0.11"
js-sys = "0.3.25"
liblumen_alloc = { path = "../../liblumen_alloc" }
liblumen_core = { path = "../../liblumen_core" }
native_implemented = { path = "../macro" }

[dependencies.liblumen_otp]
path = "../otp"
features = ["runtime_full"]

[dependencies.lumen_rt_full]
path = "../../runtimes/full"
features = ["time_web_sys"]

[dependencies.wasm-bindgen]
version = "0.2.48"
features = ["nightly"]

[dependencies.web-sys]
version = "0.3.25"
features = ["Document", "DomException", "Element", "Event", "EventListener", "EventTarget", "HtmlCollection",
            "HtmlBodyElement", "HtmlElement", "HtmlFormElement", "HtmlInputElement", "HtmlTableElement", "Node", "Text",
            "WebSocket", "Window"]

[dev-dependencies]
futures = "0.1.28"
wasm-bindgen-futures = "0.3.26"
wasm-bindgen-test = "0.2"
