name: x86_64-unknown-linux-gnu lumen/otp

on: push

jobs:
  lumen-otp:
    runs-on: ubuntu-latest
    container: kronicdeth/lumen-development@sha256:2809805464d685940b58765a634fa23a5fd1a62c65710cfa43a8791cd50fbecd

    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-toolchain-nightly-2021-01-29-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Compiler
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: lumen
      - name: lumen/otp Checkout
        run: |
          cd ..
          git init otp
          cd otp
          echo "ERL_TOP=$PWD" >> $GITHUB_ENV
          git remote add origin https://github.com/lumen/otp
          git fetch --no-tags --prune --progress --depth=1 origin +ca83f680aab717fe65634247d16f18a8cbfc6d8d:refs/remotes/origin/lumen
          git checkout --progress --force -B lumen refs/remotes/origin/lumen
      - name: lumen/otp autoconf
        run: |
          cd ../otp
          ./otp_build autoconf
      - name: lumen/otp configure
        run: |
          cd ../otp
          ./configure
      - name: Test compiling lumen/otp against liblumen_otp
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: |
            test -- --package liblumen_otp lumen::otp::
