name: x86_64-unknown-linux-gnu Libraries

on: push

jobs:
  formatted:
    runs-on: ubuntu-latest
    container: kronicdeth/lumen-development@sha256:2809805464d685940b58765a634fa23a5fd1a62c65710cfa43a8791cd50fbecd

    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-toolchain-nightly-2021-01-29-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Check Formatted
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: check-format

  libraries:
    runs-on: ubuntu-latest
    container: kronicdeth/lumen-development@sha256:2809805464d685940b58765a634fa23a5fd1a62c65710cfa43a8791cd50fbecd

    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ github.workflow }}-${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run liblumen_arena tests
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test -- --package liblumen_arena
      - name: Run liblumen_core tests
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test -- --package liblumen_core
      - name: Run liblumen_alloc tests
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test -- --package liblumen_alloc
