[package]
name = "liblumen_alloc"
version = "0.1.0"
authors = ["Paul Schoenfelder <paulschoenfelder@gmail.com>", "Luke Imhoff <Kronic.Deth@gmail.com>"]
publish = false
edition = "2018"

[features]
# Turns on allocation instrumentation
instrument = []

[dependencies]
log = "0.4"
cfg-if = "0.1"
lazy_static = "1.2"
num-traits = "0.2"
num-bigint = "0.2"
thread_local = "0.3"
heapless = { git = "https://github.com/japaric/heapless" }
liblumen_core = { path = "../liblumen_core" }
liblumen_arena = { path = "../liblumen_arena"}
liblumen_alloc_macros = { path = "../liblumen_alloc_macros" }

backtrace = "0.3.35"

[dependencies.hashbrown]
version = "0.5"
features = ["nightly"]

[dependencies.intrusive-collections]
version = "0.8"
features = ["nightly"]

[dependencies.static_assertions]
version = "0.3"
features = ["nightly"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

# for debugging
[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.20"
features = ['console']

[dev-dependencies]
pretty_assertions = "0.6"
